# Generated by Django 2.2.3 on 2019-07-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_begins', models.BooleanField()),
                ('work_ends', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('employee_id', models.IntegerField(max_length=32)),
            ],
        ),
    ]
